### DISCUSSION TITLE
`554 5.7.1 Matched map` - Can a rule provide a custom rejection message instead?

### DISCUSSION THREAD

**Discussion by polarathene** [rspamd/rspamd#5350] [Q&A] [answered]
When a [multimap module rule](https://rspamd.com/doc/modules/multimap.html#quick-start-guide) matches and the action taken results in the MTA or `rspamc` responding with context via a rejection message, how can we configure that?

I've tried searching around the docs and Github issues/discussions, but it's either not supported or I just don't know the right keywords or place to find what I'm after (_there's a lot to sift through_). The linked Rspamd docs don't seem to make any mention of such a feature and the referenced Rspamd source for the message implies it might not be supported.

I thought it might have used the more friendly `description` when present rather than the Rspamd specific reason (_understandably useful to a sysadmin for troubleshooting_).

## Reference

I want to know if it's possible to configure the `Matched map: BLOCK_SENDER_USER` portion:

`rspamc` results output:

> ```
> Message - smtp_message: Matched map: BLOCK_SENDER_USER
> ```

Or from an MTA (Postfix) with Rspamd milter configured:

> ```
> 554 5.7.1 Matched map: BLOCK_SENDER_USER
> ```

`553 5.7.1` is a generic rejection, the rejection message appears to be completely from Rspamd:

> _SMTP code "554 5.7.1" is a rejection from the receiving mail server and means email delivery is 'Not allowed' and that redelivery should not be attempted. - [Source](https://knowledge.broadcom.com/external/article/155061/message-delivery-from-messaging-gateway.html)_

Rspamd Source for the module has the following (_but it's within a `dnsbl` function call, so presumably not the source in my case_):

https://github.com/rspamd/rspamd/blob/0c53c4d2a08cc2beedd44ecb09ae63e73c00d795/src/plugins/lua/multimap.lua#L853-L859

---

## Reproduction

Two config files are used, along with `swaks` for convenience in testing (_but it could just be the raw mail file as shown further below_).

Here is a `compose.yaml` that you can copy/paste to quickly run the reproduction in a disposable container environment that can be discarded afterwards:

```yaml
services:
  rspamd:
    image: localhost/rspamd:multimap
    hostname: mail.example.test
    # Extend the official Rspamd image to bundle `swaks` for reproduction:
    pull_policy: build
    build:
      dockerfile_inline: |
        FROM rspamd/rspamd
        # Switch to root for `RUN` to be successful:
        USER root:root
        ARG DEBIAN_FRONTEND=noninteractive
        ARG SWAKS_VERSION='20240103.0'
        ARG SWAKS_RELEASE="swaks-$${SWAKS_VERSION}"
        # Install swaks (and it's perl dependencies):
        # (`$$` is to escape `$` to opt-out of Docker Compose variable interpolation feature)
        RUN << HEREDOC
          apt-get -qq update && apt-get -qq install curl nano perl libnet-dns-perl perl-doc
          curl -sSfL "https://github.com/jetmore/swaks/releases/download/v$${SWAKS_VERSION}/$${SWAKS_RELEASE}.tar.gz" | tar -xz
          mv "$${SWAKS_RELEASE}/swaks" /usr/local/bin
          rm -r "$${SWAKS_RELEASE}"
        HEREDOC
        # Restore runtime user+group back to `_rspamd`:
        USER 11333:11333
    # Custom Rspamd configs:
    configs:
      - source: rspamd-multimap
        target: /etc/rspamd/override.d/multimap.conf
      - source: rspamd-blocked-senders
        target: /etc/rspamd/custom/blocked-senders.map

configs:
  # /etc/rspamd/override.d/multimap.conf
  rspamd-multimap:
    content: |
      BLOCK_SENDER_USER {
        description = "The local-part of the address is blocked";
        action = "reject"; # Prefilter mode

        type = "from";
        # Sender adddress (from) can be sourced via `smtp` (mail envelope) or `mime` (mail header)
        extract_from = "mime";
        # Match against only the local-part of the extracted sender address:
        filter = "email:user";
        # Line delimited list of local-part values to reject:
        map = "/etc/rspamd/custom/blocked-senders.map";
      }

  # /etc/rspamd/custom/blocked-senders.map
  rspamd-blocked-senders:
    content: |
      jane.doe
```

Create a test mail to trigger the multimap rule:

```console
# Build/start the container and shell into it:
$ docker compose up -d --force-recreate
$ docker compose exec -it rspamd bash

# Produce a raw email:
$ swaks --to 'john.doe@example.test' --from 'jane.doe@example.test' --dump-mail > /tmp/example.eml
$ cat /tmp/example.eml

Date: Fri, 21 Feb 2025 00:42:05 +0000
To: john.doe@example.test
From: jane.doe@example.test
Subject: test Fri, 21 Feb 2025 00:42:05 +0000
Message-Id: <20250221004205.122253@mail.example.test>
X-Mailer: swaks v20240103.0 jetmore.org/john/code/swaks/

This is a test mailing
```

Use `rspamc` to test the mail:
- **NOTE:** If `BLOCK_SENDER_USER` instead had set `extract_from = "smtp"` (SMTP envelope FROM), you should then add the rspamc option `--from jane.doe@example.test` to provide that data.

```console
$ rspamc < /tmp/example.eml

Results for file: stdin (0.539 seconds)
[Metric: default]
Action: reject
Spam: true
Score: 1.40 / 11.00
Symbol: ARC_NA (0.00)
Symbol: BLOCK_SENDER_USER (0.00)[jane.doe]
Symbol: DBL_BLOCKED_OPENRESOLVER (0.00)[mail.example.test:mid]
Symbol: DMARC_NA (0.50)[example.test]
Symbol: FROM_EQ_ENVFROM (0.00)
Symbol: FROM_NO_DN (0.00)
Symbol: MIME_GOOD (-0.10)[text/plain]
Symbol: MIME_TRACE (0.00)[0:+]
Symbol: R_DKIM_NA (1.00)
Symbol: TO_DOM_EQ_FROM_DOM (0.00)
Message-ID: 20250221004205.122253@mail.example.test
Message - smtp_message: Matched map: BLOCK_SENDER_USER
```

For reference, this is the equivalent when sent through Postfix + rspamd milter configured (`docker-mailserver`):

```console
$ swaks --server localhost --to 'john.doe@example.test' --from 'jane.doe@example.test'

=== Trying localhost:25...
=== Connected to localhost.
<-  220 mail.example.test ESMTP
 -> EHLO mail.example.test
<-  250-mail.example.test
<-  250-PIPELINING
<-  250-SIZE 10240000
<-  250-ETRN
<-  250-ENHANCEDSTATUSCODES
<-  250-8BITMIME
<-  250 CHUNKING
 -> MAIL FROM:<jane.doe@example.test>
<-  250 2.1.0 Ok
 -> RCPT TO:<john.doe@example.test>
<-  250 2.1.5 Ok
 -> DATA
<-  354 End data with <CR><LF>.<CR><LF>
 -> Date: Thu, 20 Feb 2025 23:50:05 +0000
 -> To: john.doe@example.test
 -> From: jane.doe@example.test
 -> Subject: test Thu, 20 Feb 2025 23:50:05 +0000
 -> Message-Id: <20250220235005.116039@mail.example.test>
 -> X-Mailer: swaks v20240103.0 jetmore.org/john/code/swaks/
 ->
 -> This is a test mailing
 ->
 ->
 -> .
<** 554 5.7.1 Matched map: BLOCK_SENDER_USER
 -> QUIT
<-  221 2.0.0 Bye
=== Connection closed with remote host.
```
