### ISSUE TITLE
[Feature] Leverage Github CI for automating builds and enabling `aarch64` (ARM64) builds

### ISSUE THREAD

**Issue by polarathene** [rspamd/rspamd#4390]
## Summary

Using Github Actions CI to automate building official packages and broader platform support.

## Motivation

I have viewed the [Rspamd download docs](https://rspamd.com/downloads.html), where CentOS / Fedora docs have not been updated for years (_and [Fedora support seems to have been broken for 4-5 years](https://github.com/rspamd/rspamd.com/issues/604)_). Official Ubuntu/Debian packages are discouraged but no ARM64 builds are provided or intended to be (https://github.com/rspamd/rspamd/issues/3546#issuecomment-723503792 , https://github.com/rspamd/rspamd/issues/510).

A [maintainer has some build scripts](https://github.com/rspamd/rspamd-build-scripts). These could likely be adapted to CI builds, especially via Docker images / containers to perform the builds and output build artifacts? (_you do not need to distribute or support Docker images, just using it for a build and optionally test environment_)
- The base image can be changed to build for different versions of a distro, and likewise easily support building across different distros.
- Enables ARM64 support. It is a common practice with the Docker Github Actions to support ARM64 builds with QEMU. Base images often have ARM64 images and is transparent to you for performing the build, although when you do need additional control between AMD64 and ARM64 builds, this can also be handled within Docker easily.
- Github is likely to provide ARM64 runners in future, removing the need for QEMU (_only problematic in slow build time due to emulation_).

One additional benefit is this should better communicate when packages that are supported fail to build? Such as the Fedora support, which could then prompt resolving the issue sooner (_it's been broken for about 4-5 years or so_).

## Describe alternatives you've considered

- Installing older release (3.2) from Debian standard repos. Despite rspamd docs discouraging this, we need a ARM64 build.
- Build from source (Docker multi-stage build). Added maintenance burden, build times, and may negatively impact our CI cache management.
- Switch our base image (_inconvenient_), such as to OpenSUSE Leap for the `aarch64` OBS build. Alpine could be an option, but we'd rather avoid issues that can cause (_like with `musl`_).

## Additional context

I am a maintainer of [`docker-mailserver`](https://github.com/docker-mailserver/docker-mailserver/) (_On [DockerHub with 5M pulls](https://hub.docker.com/r/mailserver/docker-mailserver/), plus more than 50M pulls before the switch to a GH org at the old image `tvial/docker-mailserver`](https://hub.docker.com/r/tvial/docker-mailserver/)_), a popular Docker image for setting up a mail-server.

We are bringing `rspamd` into the next release (_with the intention to replace existing Amavis + SpamAssassin_), but ARM64 support lacks an official build, so [**we're pulling in an older version (3.2) from the Debian Bullseye repo**](https://github.com/docker-mailserver/docker-mailserver/pull/3059#discussion_r1097982580), despite being discouraged there is **no official alternative** for us there.

Hence reaching out to upstream here to discuss improving build and platform support via CI (Github Actions).

**Comment by vstakhov** [comment]
I do agree with your points: the current build system is outdated and very limited. I have created it when there was no sane tools nor CPU capacities we have now. I'm not quite sure that Github CI is the best tool for that purposes, probably, I should deploy Gitlab with it's self-hosted CI. Unfortunately, I'm not very familiar with these setups, but I think that building packages on each commit and on each tag is a fantastic option that should be doable in theory. Also a question to @citrin with regard to the existing Drone CI capacities: can we build packages for the mainstream Linux distros and optimally for another architecture (specifically, arm64)? It doesn't matter if we need some additional VMs for that (e.g. EC2 arm64 nodes).

**Comment by polarathene** [comment]
> I'm not quite sure that Github CI is the best tool for that purposes, probably, I should deploy Gitlab with it's self-hosted CI.
> Unfortunately, I'm not very familiar with these setups, but I think that building packages on each commit and on each tag is a fantastic option that should be doable in theory.

I am quite familiar with Github CI, and it has plenty of community support to make implementing such easier. I am not familiar with Gitlab CI and if it has something equivalent to [Github Marketplace - Actions](https://github.com/marketplace?type=actions). It is basically an ecosystem of "packages" which can provide common / popular functionality instead of implementing and maintaining at a lower level.

At `docker-mailserver` we have been using Github Actions for CI quite successfully since it replaced Travis. It is great for our test suite to give feedback on PRs, generate preview documentation contributions, and automate builds and releases (when merging into master or tagging a release).

I am also quite experienced with Docker, so I'm happy to collaborate if you'd like the assistance setting it up.

---

> I'm not quite sure that Github CI is the best tool for that purposes, probably, I should deploy Gitlab with it's self-hosted CI.
> with regard to the existing Drone CI capacities: can we build packages for the mainstream Linux distros and optimally for another architecture (specifically, arm64)? It doesn't matter if we need some additional VMs for that (e.g. EC2 arm64 nodes).

If you've already got CI setup elsewhere and that is working well, no worries :+1: 

---

This is basically all there is to [building a Docker image with AMD64 + ARM64](https://github.com/docker-mailserver/docker-mailserver/blob/9e9f8026d9260db89da37b555b16975fb8cb2ae7/.github/workflows/generic_build.yml#L76-L100) in Github CI. Here's a rough minimal snippet:

```yaml
      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v2.1.0
        with:
          platforms: arm64

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2.4.0

      - name: 'Build images'
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
```

We have separate workflows for handling build, test and publish, which are re-usable across our main CI workflows that are triggered by PR activity or [pushing to master or tagging a release](https://github.com/docker-mailserver/docker-mailserver/blob/9e9f8026d9260db89da37b555b16975fb8cb2ae7/.github/workflows/default_on_push.yml):

```yaml
jobs:
  build-image:
    name: 'Build AMD64 Image'
    uses: docker-mailserver/docker-mailserver/.github/workflows/generic_build.yml@master

  run-tests:
    name: 'Test AMD64 Image'
    needs: build-image
    uses: docker-mailserver/docker-mailserver/.github/workflows/generic_test.yml@master
    with:
      cache-key: ${{ needs.build-image.outputs.build-cache-key }}

  publish-images:
    name: 'Publish AMD64 and ARM64 Image'
    needs: [build-image, run-tests]
    uses: docker-mailserver/docker-mailserver/.github/workflows/generic_publish.yml@master
    with:
      cache-key: ${{ needs.build-image.outputs.build-cache-key }}
    secrets: inherit
```

Github CI also supports self-hosted runners, but I do not have experience with those. I just wanted to highlight how simple it is with Github to manage vs your own infrastructure and alternative tooling.
